declare module 'vtex.product-context/useProduct';
declare module 'vtex.order-items/OrderItems';
declare module 'vtex.pixel-manager/PixelContext';
declare module 'vtex.styleguide';
declare module 'vtex.order-manager';
declare module 'vtex.pixel-manager';
declare module 'vtex.render-runtime';
declare module 'vtex.slider-layout/SliderLayout';
declare module 'vtex.product-summary-context';
declare module 'vtex.modal-layout/ModalTrigger';
declare module 'vtex.modal-layout/Modal';
declare module 'vtex.modal-layout/ModalHeader';
declare module 'vtex.rich-text/index';
declare module 'vtex.store-image/Image';
declare module 'vtex.store-components';
declare module 'vtex.search-page-context/SearchPageContext'